name = "MINECRAFT DOS PATETAS"
author = "SABINO"
version = "1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9fda840c9fea5b1ecfef07eb5f903796065b096a611ee2c6340799a37dd735cc"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
