name = "MINECRAFT DOS PATETAS"
author = "SABINO"
version = "1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85110e380ef5182b3e6d5ca0fef0a2f1570ab5465c1f4fa670fb63fca555ba74"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
